# Generated by Django 3.2.9 on 2021-12-01 03:35

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=social.models.random_image, upload_to='uploads/profile_pictures'),
        ),
    ]
