# Generated by Django 3.2.9 on 2021-12-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
